# Generated by Django 3.2 on 2022-11-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplomatura', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='producto',
            new_name='nombre',
        ),
    ]
